<?php
/**
 * Created by PhpStorm.
 * User: lwx
 * Date: 2018/9/18
 * Time: 12:20
 * Desc: 过滤器  记录动作执行时间日志
 */
namespace app\components;

use  Yii;
use yii\base\ActionFilter;

class ActionTimeFilter extends ActionFilter
{
    private $_startTime;

    public function beforeAction($action)
    {
        $this->_startTime = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $time = microtime(true) - $this->_startTime;
        Yii::debug("Action '{$action->uniqueId}' spent $time second.");
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}